[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79

[project]
name = "chessresults"
version = "7.1.1"
authors = [
  { name="Roger Marsh", email="roger.marsh@solentware.co.uk" },
]
description = "Results database for chess games."
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Games/Entertainment :: Board Games",
    "Intended Audience :: End Users/Desktop",
    "Development Status :: 3 - Alpha",
]
license = {file = "LICENCE"}
readme = "README"
dependencies = [
    "chesscalc==1.3.4",
    "chessvalidate==2.0.2",
    "solentware-base==5.1",
    "solentware-grid==2.1.10",
]

[project.urls]
Homepage = "http://www.solentware.co.uk"
Repository = "https://github.com/RogerMarsh/chessresults.git"
"Bug Tracker" = "https://github.com/RogerMarsh/chessresults/issues"

[tool.setuptools]
packages = [
    "chessresults",
    "chessresults.core",
    "chessresults.core.ecf",
    "chessresults.core.ogd",
    "chessresults.help_",
    "chessresults.basecore",
    "chessresults.minorbases",
    "chessresults.gui",
    "chessresults.gui.ecf",
    "chessresults.gui.lite",
    "chessresults.gui.ogd",
    "chessresults.gui.minorbases",
    "chessresults.lmdb",
    "chessresults.berkeleydb",
    "chessresults.db",
    "chessresults.db_tkinter",
    "chessresults.dpt",
    "chessresults.sqlite",
    "chessresults.apsw",
    "chessresults.unqlite",
    "chessresults.vedis",
    "chessresults.tools",
]

[tool.setuptools.package-data]
chessresults = ["help_/*.txt"]
